PATCH http://localhost:3000/posts
Content-Type: application/json

{
    "email":"jdou@void.net",
    "message":"Laborum molestias illo. Expedita consequatur sit eius quas suscipit vel et pariatur doloribus. Aperiam est eius. Itaque temporibus ut natus nihil et eligendi autem aliquid enim. Aut officia quis. Nihil voluptas aperiam eos cumque tempore eveniet quo.",
    "date":"Tue Jul 07 2020 04:09:35 GMT+0300 (Восточная Европа, летнее время)"
}